version: "3"
services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6381:6379"  # Use default Redis port

  app:
    build: .
    container_name: url-shortener
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
